### ISSUE TITLE
AssertionError: Invalid value yc.driver(4,) in domain term ('driver_id', '=', yc.driver(4,))

### ISSUE THREAD

**Issue by ARJhe** [ARJhe/odoo11#1]
2019-03-07 01:50:53,237 12096 INFO odoo11 werkzeug: 127.0.0.1 - - [07/Mar/2019 01:50:53] "POST /web/dataset/call_kw/yc.driver/name_search HTTP/1.1" 200 -
2019-03-07 01:50:54,868 12096 ERROR odoo11 odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\odoo\odoo11\odoo-11.0\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 5195, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 5021, in _onchange_eval
    method_res = method(self)
  File "d:\odoo\odoo11\addons_yc\yc_produce\models\produce.py", line 89, in _generate_carno
    check = rec.env["yc.weight"].search([('driver_id', '=', rec.driver_id), ('day', '=', check_day)])
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 1481, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 3795, in _search
    query = self._where_calc(args)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 3587, in _where_calc
    where_clause, where_params = e.to_sql()
  File "D:\odoo\odoo11\odoo-11.0\odoo\osv\expression.py", line 1271, in to_sql
    q, ps = self.__leaf_to_sql(leaf)
  File "D:\odoo\odoo11\odoo-11.0\odoo\osv\expression.py", line 1165, in __leaf_to_sql
    "Invalid value %r in domain term %r" % (right, leaf)
AssertionError: Invalid value yc.driver(4,) in domain term ('driver_id', '=', yc.driver(4,))
2019-03-07 01:50:54,873 12096 INFO odoo11 werkzeug: 127.0.0.1 - - [07/Mar/2019 01:50:54] "POST /web/dataset/call_kw/yc.weight/onchange HTTP/1.1" 200 -
2019-03-07 01:52:58,259 12096 INFO odoo11 werkzeug: 127.0.0.1 - - [07/Mar/2019 01:52:58] "POST /web/dataset/call_kw/yc.driver/name_search HTTP/1.1" 200 -
2019-03-07 01:53:00,141 12096 ERROR odoo11 odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\odoo\odoo11\odoo-11.0\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 5195, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 5021, in _onchange_eval
    method_res = method(self)
  File "d:\odoo\odoo11\addons_yc\yc_produce\models\produce.py", line 89, in _generate_carno
    check = rec.env["yc.weight"].search([('driver_id', '=', rec.driver_id), ('day', '=', check_day)])
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 1481, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 3795, in _search
    query = self._where_calc(args)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 3587, in _where_calc
    where_clause, where_params = e.to_sql()
  File "D:\odoo\odoo11\odoo-11.0\odoo\osv\expression.py", line 1271, in to_sql
    q, ps = self.__leaf_to_sql(leaf)
  File "D:\odoo\odoo11\odoo-11.0\odoo\osv\expression.py", line 1165, in __leaf_to_sql
    "Invalid value %r in domain term %r" % (right, leaf)
AssertionError: Invalid value yc.driver(3,) in domain term ('driver_id', '=', yc.driver(3,))
2019-03-07 01:53:00,143 12096 INFO odoo11 werkzeug: 127.0.0.1 - - [07/Mar/2019 01:53:00] "POST /web/dataset/call_kw/yc.weight/onchange HTTP/1.1" 200 -
2019-03-07 01:53:04,252 12096 INFO odoo11 werkzeug: 127.0.0.1 - - [07/Mar/2019 01:53:04] "POST /web/dataset/call_kw/yc.driver/name_search HTTP/1.1" 200 -
2019-03-07 01:53:05,088 12096 ERROR odoo11 odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\odoo\odoo11\odoo-11.0\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 5195, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 5021, in _onchange_eval
    method_res = method(self)
  File "d:\odoo\odoo11\addons_yc\yc_produce\models\produce.py", line 89, in _generate_carno
    check = rec.env["yc.weight"].search([('driver_id', '=', rec.driver_id), ('day', '=', check_day)])
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 1481, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 3795, in _search
    query = self._where_calc(args)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 3587, in _where_calc
    where_clause, where_params = e.to_sql()
  File "D:\odoo\odoo11\odoo-11.0\odoo\osv\expression.py", line 1271, in to_sql
    q, ps = self.__leaf_to_sql(leaf)
  File "D:\odoo\odoo11\odoo-11.0\odoo\osv\expression.py", line 1165, in __leaf_to_sql
    "Invalid value %r in domain term %r" % (right, leaf)
AssertionError: Invalid value yc.driver(4,) in domain term ('driver_id', '=', yc.driver(4,))
2019-03-07 01:53:05,090 12096 INFO odoo11 werkzeug: 127.0.0.1 - - [07/Mar/2019 01:53:05] "POST /web/dataset/call_kw/yc.weight/onchange HTTP/1.1" 200 -

----------------------------------------------------produce.py---------------------------------------------------

        # S5
        for rec in self:
            if rec.driver_id:
                check_day = dt.strptime(rec.day, "%Y-%m-%d")
                check = rec.env["yc.weight"].search([('driver_id', '=', rec.driver_id), ('day', '=', check_day)])
                if check:
                    S5 = len(check)
                else:
                    S5 = 1

                if S1 and S2 and S3 and S4 and S5:
                    self.carno = str(S1 + S2 + S3 + S4 + S5)
                else:
                    pass

        else:
            pass

**Comment by ARJhe** [comment]
whole function:

    carno = fields.Char("車次序號", compute="_generate_carno", store=True)

    # carno = S1+S2+S3+S4+S5
    @api.onchange("driver_id")
    def _generate_carno(self):

        year = str(dt.now().year)
        month = "%02d" % (dt.now().month)
        day = "%02d" % (dt.now().day)
        # S1
        if year[3:] == "0":
            S1 = "A"
        elif year[3:] == "1":
            S1 = "B"
        elif year[3:] == "2":
            S1 = "C"
        elif year[3:] == "3":
            S1 = "D"
        else:
            S1 = year[3:]

        # S2
        if month == "10":
            S2 = "A"
        elif month == "11":
            S2 = "B"
        elif month == "12":
            S2 = "C"
        else:
            S2 = month[1:]

        # S3
        day_list = ['1', '2', '3', '4', '5', '6', '7', '8', '9', 'A',
                    'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K',
                    'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V']
        S3 = day_list[int(day) - 1]

        # S4
        for rec in self:
            if rec.driver_id:
                S4 = rec.env["yc.driver"].search([('name', '=', self.driver_id.name)]).code
            else:
                pass

        # S5
        for rec in self:
            if rec.driver_id:
                check_day = dt.strptime(rec.day, "%Y-%m-%d")
                check = rec.env["yc.weight"].search([('driver_id', '=', rec.driver_id), ('day', '=', check_day)])
                if check:
                    S5 = len(check)
                else:
                    S5 = 1

                if S1 and S2 and S3 and S4 and S5:
                    self.carno = str(S1 + S2 + S3 + S4 + S5)
                else:
                    pass

        else:
            pass

**Comment by ARJhe** [comment]
SOLVED:
check = rec.env["yc.weight"].search([('driver_id', '=',[rec.driver_id.name](#)), ('day', '=', check_day)])
