### ISSUE TITLE
overwrite name_get() cause import db api get wrong "name"

### ISSUE THREAD

**Issue by ARJhe** [ARJhe/odoo11#12]
when I finished module YcWeight and YcWeightDetails then I wrote an api which can import data(過磅單and過磅單主檔) from origin db,
it fetch "name"(單號) as key to download data from db.

since I overwrote the name_get function this api fetch wrong name.
```python
@api.multi
def name_get(self):
    result = []
    for record in self:
        name = record.carno
        result.append((record.id, name))
    return result
```

**Comment by ARJhe** [comment]
[solution](https://www.odoo.com/fr_FR/forum/aide-1/question/how-to-add-condition-for-particular-class-to-show-field-drop-down-except-partner-id-from-res-partner-form-124809)

**Comment by ARJhe** [comment]
Traceback (most recent call last):
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\odoo\odoo11\odoo-11.0\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 1563, in name_search
    return self._name_search(name, args, operator, limit=limit)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 1578, in _name_search
    return recs.sudo(access_rights_uid).name_get()
  File "d:\odoo\odoo11\addons_yc\yc_root\models\weight.py", line 217, in name_get
    if not self._context.get('params'):
TypeError: 'NoneType' object is not subscriptable

**Comment by ARJhe** [comment]
```python
@api.multi
def name_get(self):
    result = []
    for record in self:
        # 轉檔時 self._context.get('params')['action'] = 107
        # 過磅時 self._context.get('params')['action'] = 82
        # 進貨時 self._context.get('params')['action'] = None
        if not self._context.get('params'):
            name = record.carno
            result.append((record.id, name))
        else:
            name = record.name
            result.append((record.id, name))

    return result
```
