### ISSUE TITLE
During handling of the above exception, another exception occurred

### ISSUE THREAD

**Issue by ARJhe** [ARJhe/odoo11#17]
```
2019-04-25 08:38:15,726 2848 INFO odoo11 werkzeug: 127.0.0.1 - - [25/Apr/2019 08:38:15] "POST /web/dataset/call_kw/yc.weight/read HTTP/1.1" 200 -
2019-04-25 08:38:15,745 2848 ERROR odoo11 odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "D:\odoo\odoo11\odoo-11.0\odoo\fields.py", line 939, in __get__
    value = record.env.cache.get(record, self)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 967, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 623740

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\odoo\odoo11\odoo-11.0\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 2608, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 4785, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "D:\odoo\odoo11\odoo-11.0\odoo\fields.py", line 946, in __get__
    value = record.env.cache.get(record, self)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 967, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 623740
2019-04-25 08:38:15,748 2848 INFO odoo11 werkzeug: 127.0.0.1 - - [25/Apr/2019 08:38:15] "POST /web/dataset/call_kw/yc.weight.details/read HTTP/1.1" 200 -
2019-04-25 08:38:32,538 2848 INFO odoo11 werkzeug: 127.0.0.1 - - [25/Apr/2019 08:38:32] "POST /longpolling/poll HTTP/1.1" 200 -
2019-04-25 08:38:43,618 2848 INFO odoo11 werkzeug: 127.0.0.1 - - [25/Apr/2019 08:38:43] "POST /longpolling/poll HTTP/1.1" 200 -
2019-04-25 08:39:33,664 2848 INFO odoo11 werkzeug: 127.0.0.1 - - [25/Apr/2019 08:39:33] "POST /longpolling/poll HTTP/1.1" 200 -
2019-04-25 08:39:42,102 2848 INFO odoo11 odoo.sql_db: ConnectionPool(used=2/count=11/max=64): Closed 1 connections to 'sslmode=prefer dbname=odoo10 password=xxx host=localhost user=odoo port=5432'
2019-04-25 08:39:42,246 2848 WARNING odoo11 odoo.sql_db: Cursor not closed explicitly
Please enable sql debugging to trace the caller.
```

**Comment by ARJhe** [comment]
[refer](https://www.odoo.com/forum/help-1/question/hi-guys-my-app-can-t-work-it-gives-a-keyerror-129656)：
This issue is shown by Odoo when it cannot find a model (or a field).
--
```python
compute_no = fields.Integer("最大數", compute= "_get_row_no")

@api.depends("no")
    def _get_row_no(self):
        if self.ids:
            count =1
            for rec in self:
                weight_id = self.env['yc.weight.details'].search([('id','=', rec.id)])
                weight_id.write({'no': count})
                count += 1
```
to disable the compute function, Issue resolved.

**Comment by ARJhe** [comment]
![marty-mcfly](https://i.imgur.com/etKzzIo.png)
