### ISSUE TITLE
AssertionError: Invalid value yc.weight() in domain term ('name', '=', yc.weight())

### ISSUE THREAD

**Issue by ARJhe** [ARJhe/odoo11#26]
create a weight record, then save and edit it to add new weight detail item.
while save occur this error.
```
Traceback (most recent call last):
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\odoo\odoo11\odoo-11.0\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "d:\odoo\odoo11\addons_yc\yc_root\models\weight.py", line 216, in write
    return super(YcWeight, self).write(vals)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 3109, in write
    self._write(old_vals)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 3249, in _write
    field.write(self.with_context(rel_context), vals[name])
  File "D:\odoo\odoo11\odoo-11.0\odoo\fields.py", line 2279, in write
    comodel.create(act[2])
  File "d:\odoo\odoo11\addons_yc\yc_root\models\weight.py", line 281, in create
    number = len(self.env["yc.weight.details"].search([("name","=",self.name)]))
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 1481, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 3795, in _search
    query = self._where_calc(args)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 3587, in _where_calc
    where_clause, where_params = e.to_sql()
  File "D:\odoo\odoo11\odoo-11.0\odoo\osv\expression.py", line 1271, in to_sql
    q, ps = self.__leaf_to_sql(leaf)
  File "D:\odoo\odoo11\odoo-11.0\odoo\osv\expression.py", line 1165, in __leaf_to_sql
    "Invalid value %r in domain term %r" % (right, leaf)
AssertionError: Invalid value yc.weight() in domain term ('name', '=', yc.weight())
```

**Comment by ARJhe** [comment]
```python
            if rec.in_out:  # 進出貨有值
                if driver and rec.day:
                    self.ship_times = len(check_out)
                    self.purchase_times = len(check_in)
                    # 新增模式(db無單號)
                    if not self.env["yc.weight"].search([("name", "=", self.name)]):
                        if rec.in_out == 'I':
                            rec.ship_times = self.ship_times
                            rec.purchase_times = self.purchase_times + 1
                        elif rec.in_out == 'O':
                            # onchange decorator 要存到db 需要rec.field = self.field 這種寫法 ps.只有新增有用
                            rec.ship_times = self.ship_times + 1
                            rec.purchase_times = self.purchase_times
                    else: # 修改模式 無法儲存 要另寫compute 更新資料
                        if rec.in_out == 'I':
                            rec.ship_times = self.ship_times
                            rec.purchase_times = self.purchase_times +1
                        elif rec.in_out == 'O':
                            rec.ship_times = self.ship_times
                            rec.purchase_times = self.purchase_times +1
```

**Comment by ARJhe** [comment]
### solved:
L#3
```
number = len(self.env["yc.weight.details"].search([("name","=",self.name)]))
```
can not fetch data of self.name in create mode
```python
    @api.model
    def create(self, vals):
        number = len(self.env["yc.weight.details"].search([("name","=",self.name)]))
        vals.update({"no": number })
        return super(YcWeightDetails, self).create(vals)
```
