### ISSUE TITLE
Wizard Error

### ISSUE THREAD

**Issue by ARJhe** [ARJhe/odoo11#31]
Error
```
Odoo Server Error
Traceback (most recent call last):
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\odoo\odoo11\odoo-11.0\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 685, in call_kw
    method = getattr(type(model), name)
AttributeError: type object 'yc.purchase' has no attribute '154'
```

**Comment by ARJhe** [comment]
```xml
<button string="搜尋舊檔" type="object" class="oe_highlight" name="%(action_purchase_wizard)d"/>
```
wrong button type, should be action.
--
view/purchase.xml(use button to call wizard)
```xml
<button string="搜尋舊檔" type="action" class="oe_highlight" name="%(action_purchase_wizard)d"/>
```
wizard/purchase_wizard.xml (target view)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <record model="ir.ui.view" id="purchase_wizard">
        <field name="name">Purchase Report</field>
        <field name="model">purchase.wizard</field>
        <!--<field name="type">form</field>-->
        <field name="arch" type="xml">
            <form string="Purchase Report">
                <group>
                </group>
                <footer>
                    <button name="" string="comfirm" type="object" class="oe_highlight"/>
                    <button string="Cancel" special="cancel"/>
                </footer>
            </form>
        </field>
    </record>
    <record id="action_purchase_wizard" model="ir.actions.act_window">
        <field name="name">Open Wizard</field>
        <field name="res_model">purchase.wizard</field>
        <field name="view_type">form</field>
        <field name="view_mode">form</field>
        <field name="target">new</field>
    </record>
</odoo>
```
wizard/purchase_wizard.py
```python
# -*- coding: utf-8 -*-
from odoo import models, fields, api
class PurchaseWizard(models.TransientModel):
    _name = 'purchase.wizard'
```
wizard/＿init＿.py
```python
# -*- coding: utf-8 -*-
from . import purchase_wizard
```

**Comment by ARJhe** [comment]
Reference
--
[Create wizard in Odoo v10](http://palkeshbaraiya.blogspot.com/2017/04/create-wizard-in-odoo-v10.html)
