### ISSUE TITLE
pass self.env.user object when open a view

### ISSUE THREAD

**Issue by ARJhe** [ARJhe/odoo11#37]
```
Uncaught Error: NameError: name 'user' is not defined
http://localhost:8069/web/content/3986-c511197/web.assets_backend.js:144
追溯:
Error: NameError: name 'user' is not defined
    at PY_ensurepy (http://localhost:8069/web/content/3986-c511197/web.assets_backend.js:144:65)
    at Object.py.evaluate (http://localhost:8069/web/content/3986-c511197/web.assets_backend.js:259:8)
    at Object.py.evaluate (http://localhost:8069/web/content/3986-c511197/web.assets_backend.js:270:25)
    at Object.py.evaluate (http://localhost:8069/web/content/3986-c511197/web.assets_backend.js:270:25)
    at Object.py.evaluate (http://localhost:8069/web/content/3986-c511197/web.assets_backend.js:265:111)
    at Object.py.evaluate (http://localhost:8069/web/content/3986-c511197/web.assets_backend.js:267:99)
    at Object.py.eval (http://localhost:8069/web/content/3986-c511197/web.assets_backend.js:272:284)
    at http://localhost:8069/web/content/3986-c511197/web.assets_backend.js:380:136
    at Function._.each._.forEach (http://localhost:8069/web/content/3985-c19f1f2/web.assets_common.js:12:558)
    at _.<computed> [as each] (http://localhost:8069/web/content/3985-c19f1f2/web.assets_common.js:69:526)
```

```xml
<record model="ir.actions.act_window" id="weight_list_action">
            <field name="name">過磅單作業</field>
            <field name="type">ir.actions.act_window</field>
            <field name="res_model">yc.weight</field>
            <field name="view_type">form</field>
            <field name="view_mode">tree,form</field>
            <field name="domain">[('factory_id','=', user.factory_id.id)]</field>
        </record>
```

**Comment by ARJhe** [comment]
Reference
--
[Window Action domain, 'user' is not defined](https://www.odoo.com/fr_FR/forum/aide-1/question/window-action-domain-user-is-not-defined-119235)

**Comment by ARJhe** [comment]
### Solution
1. add ir.actions.server to which view you want to manipulate.
```xml
        <!-- getcontext -->
        <record id="weight_filter_act" model="ir.actions.server">
            <field name="name">使用者廠別動態過濾</field>
            <field name="model_id" ref="yc_root.weight_list_action_tree"/>
            <field name="state">code</field>
            <field name="code">action = model.factory_filter()</field>
        </record>
```
You should notice the model_id refer to the correct name in ir.model.
```xml
<field name="model_id" ref="module_name.action_id"/>
```
2. define the action and attach user context
```python
    @api.model
    def factory_filter(self):
        ctx = self.env.context.copy()
        ctx.update({'factory_id': self.env.user.factory_id.id})
        return {
            'name': '使用者廠別動態過濾',
            'view_type': 'tree',
            'view_mode': 'tree,form',
            'res_model': 'yc.weight',
            'type': 'ir.actions.act_window',
            'view_id': self.env.ref('yc_root.weight_list_action_tree').id,
            'context': dict(ctx),
        }
```
3. add restriction to domain
```xml
        <record model="ir.actions.act_window" id="weight_list_action">
            <field name="name">過磅單作業</field>
            <field name="type">ir.actions.act_window</field>
            <field name="res_model">yc.weight</field>
            <field name="view_type">form</field>
            <field name="view_mode">tree,form</field>
            <field name="domain">[("factory_id","=",context.get('factory_id'))]</field>
            <field name="context">{}</field>
        </record>
```
highlight
```xml
            <field name="domain">[("factory_id","=",context.get('factory_id'))]</field>
```
