### ISSUE TITLE
Update code to server return error

### ISSUE THREAD

**Issue by ARJhe** [ARJhe/odoo11#41]
```
2019-06-12 09:36:25,064 29092 INFO erp-0522 odoo.addons.base.ir.ir_cron: Starting job `Base: Auto-vacuum internal data`.
2019-06-12 09:36:25,065 29092 ERROR erp-0522 odoo.sql_db: bad query: b'SELECT "res_users"."id" as "id","res_users"."partner_id" as "partner_id","res_users"."alias_id" as "alias_id","res_users"."notification_type" as "notification_type","res_users"."password_crypt" as "password_crypt","res_users"."company_id" as "company_id","res_users"."write_uid" as "write_uid","res_users"."active" as "active","res_users"."write_date" as "write_date","res_users"."chatter_position" as "chatter_position","res_users"."create_uid" as "create_uid","res_users"."password" as "password","res_users"."signature" as "signature","res_users"."create_date" as "create_date","res_users"."factory_id" as "factory_id","res_users"."share" as "share","res_users"."login" as "login","res_users"."action_id" as "action_id" FROM "res_users" WHERE "res_users".id IN (1)'
ERROR: column res_users.factory_id does not exist
LINE 1: ...ature","res_users"."create_date" as "create_date","res_users...
                                                             ^

2019-06-12 09:36:25,066 29092 ERROR erp-0522 odoo.addons.base.ir.ir_cron: Unexpected exception while processing cron job {'id': 1, 'ir_actions_server_id': 28, 'cron_name': 'Base: Auto-vacuum internal data', 'user_id': 1, 'active': True, 'interval_number': 1, 'interval_type': 'days', 'numbercall': -1, 'doall': False, 'nextcall': '2019-06-12 09:13:18', 'priority': 5, 'create_uid': 1, 'create_date': '2019-03-04 09:13:07.411669', 'write_uid': 1, 'write_date': '2019-05-09 03:27:16.614589'}
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/odoo/odoo-server/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7f7c0a8577b8>, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/fields.py", line 937, in __get__
    value = record.env.cache.get(record, self)
  File "/odoo/odoo-server/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: (<odoo.sql_db.Cursor object at 0x7f7c0a8577b8>, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_cron.py", line 223, in _process_jobs
    registry[cls._name]._process_job(job_cr, job, lock_cr)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_cron.py", line 129, in _process_job
    now = fields.Datetime.context_timestamp(cron, datetime.now())
  File "/odoo/odoo-server/odoo/fields.py", line 1577, in context_timestamp
    tz_name = record._context.get('tz') or record.env.user.tz
  File "/odoo/odoo-server/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/odoo/odoo-server/odoo/fields.py", line 1052, in determine_value
    self.compute_value(recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1008, in compute_value
    self._compute_value(records)
  File "/odoo/odoo-server/odoo/fields.py", line 1001, in _compute_value
    self.compute(records)
  File "/odoo/odoo-server/odoo/fields.py", line 586, in _compute_related
    values = [first(value[name]) for value in values]
  File "/odoo/odoo-server/odoo/fields.py", line 586, in <listcomp>
    values = [first(value[name]) for value in values]
  File "/odoo/odoo-server/odoo/models.py", line 4758, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/odoo/odoo-server/odoo/fields.py", line 941, in __get__
    self.determine_value(record)
  File "/odoo/odoo-server/odoo/fields.py", line 1042, in determine_value
    record._prefetch_field(self)
  File "/odoo/odoo-server/odoo/models.py", line 2646, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/odoo/odoo-server/odoo/addons/base/res/res_users.py", line 924, in read
    res = super(UsersView, self).read(other_fields, load=load)
  File "/odoo/odoo-server/odoo/addons/base/res/res_users.py", line 320, in read
    return super(Users, self).read(fields=fields, load=load)
  File "/odoo/odoo-server/odoo/models.py", line 2590, in read
    self._read_from_database(stored, inherited)
  File "/odoo/odoo-server/odoo/addons/base/res/res_users.py", line 285, in _read_from_database
    super(Users, self)._read_from_database(field_names, inherited_field_names)
  File "/odoo/odoo-server/odoo/models.py", line 2709, in _read_from_database
    cr.execute(query_str, params)
  File "/odoo/odoo-server/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column res_users.factory_id does not exist
LINE 1: ...ature","res_users"."create_date" as "create_date","res_users...
```

**Comment by ARJhe** [comment]
backup local server db data and restore to server.
