### ISSUE TITLE
How to copy all fields's value from one record into another?

### ISSUE THREAD

**Issue by ARJhe** [ARJhe/odoo11#51]
the number of fields in one record has near 400, how could I insert value from the record I choice into other record without manually assign?
![2019-06-27 (3)](https://user-images.githubusercontent.com/34853697/60253107-1f8d9b80-98fe-11e9-9cf8-2deb76ab05d7.png)

```python
_id = self._context.get('active_ids')
purchase = self.env['yc.purchase'].search([('id','=', _id)])
copy = wizard_checked.copy()
purchase.write(copy)
```
```
Traceback (most recent call last):
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\odoo\odoo11\odoo-11.0\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 334, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "d:\odoo\odoo11\addons_yc\yc_root\wizard\purchase_wizard.py", line 130, in comfirm
  File "d:\odoo\odoo11\addons_yc\yc_root\models\purchase.py", line 899, in write
    return super(YcPurchase, self).write(vals)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 3085, in write
    vals.pop(field, None)
AttributeError: 'yc.purchase' object has no attribute 'pop'
```

**Comment by ARJhe** [comment]
```python
_id = self._context.get('active_ids')
purchase = self.env['yc.purchase'].search([('id', '=', _id)])
# 把欄位名稱都讀出來 到a字典
#  for loop: a.write({k :a['dic.key']})
_fields = []
for key in wizard_checked._proper_fields._map.keys():
    _fields.append(key)
for _f in _fields:
    # M2O has attr 'id'
    if hasattr(wizard_checked[_f],'id'):
        purchase.write({_f: wizard_checked[_f].id})
    else:
        purchase.write({_f: wizard_checked[_f]})

```

**Comment by ARJhe** [comment]
`Your solution work but have a lot of issue you are calling a write for each field you can keep value in dictionary then call write one time at the end. Checkout my edit – EasyOdoo`
```python
a = self.browse(a)
b = self.browse(b)
# read all field_name in to a list
_fields = []
for fn in self._proper_fields._map.keys():
    _fields.append(fn)
# start to write
vals = {}
for _f in _fields:
    # M2O must use id
    if hasattr(b[_f],'id'):
        # a.write({_f: b[_f].id})
        vals.update({_f: b[_f].id})
    else:
        # a.write({_f: b[_f]})
        vals.update({_f: b[_f]})

a.write(vals)
```
