### ISSUE TITLE
No way back in in Try-except function

### ISSUE THREAD

**Issue by ARJhe** [ARJhe/odoo11#7]
```python
    # 過磅單主檔轉資料庫 ERPALL > pgsql
    @api.multi
    def insert_yc_weight(self):
        try:
            cnxn = pyodbc.connect('DRIVER={SQL Server}; SERVER=220.133.113.223,1433; DATABASE=ERPALL; UID=erplogin; PWD=@53272162')
            cursor = cnxn.cursor()
            cursor.execute("SELECT * FROM 過磅單主檔")
            rows = cursor.fetchall()
            weight = self.env["yc.weight"].search([])
            sql = "delete from yc_weight"
            self._cr.execute(sql)



            for row in rows:
                driver_id = self.env["yc.driver"].search([("code", '=', row.司機代號)])
                person_id = self.env["yc.hr"].search([("code", '=', row.過磅人員)])
                factory_id = self.env["yc.factory"].search([("name", '=', row.所屬工廠)])
                weight.create({
                    "name": row.過磅單號,
                    "in_out": row.分類,
                    "driver_id": driver_id.id,
                    "day": row.日期,
                    "weightime": row.時間,
                    "carno": row.車次序號,
                    "person_id": person_id.id,
                    "weighbridge": row.地磅序號,
                    "plate_no": row.車號,
                    "refine": row.調質重量,
                    "total": row.總重,
                    "carbur": row.滲碳重量,
                    "curbweight": row.空車重,
                    "other": row.其他重量,
                    "emptybucket": row.空桶重,
                    "net": row.淨重,
                    "purchase_times": row.進貨次數,
                    "ship_times": row.出貨次數,
                    "note": row.備註,
                    "other1": row.其他重量1,
                    "factory_id": factory_id.id,
                })

            cursor.execute("SELECT * FROM 過磅單項目檔")
            rows = cursor.fetchall()
            weight_item = self.env["yc.weight.details"].search([])
            sql = "delete from yc_weight_details"
            self._cr.execute(sql)

            for row in rows:
                customer_id = self.env["yc.customer"].search([("code", '=', row.客戶代號)])
                processing_id = self.env["yc.processing"].search([("code", '=', row.加工廠代號)])
                weight_item.create({
                    "name": row.過磅單號,
                    "no": row.序號,
                    "客戶代號": customer_id.id,
                    "加工廠代號": processing_id.id,
                    "note": row.備註,
                })


        except Exception as e:
            pass
        return True
```

**Comment by ARJhe** [comment]
[From stackoverflow:](https://stackoverflow.com/questions/19522990/python-catch-exception-and-continue-try-block/19523054)
---
No, you cannot do that. That's just the way Python has its syntax. Once you exit a try-block because of an exception, there is no way back in.

What about a for-loop though?
```python
funcs = do_smth1, do_smth2

for func in funcs:
    try:
        func()
    except Exception:
        pass  # or you could use 'continue'
```
Note however that it is considered a bad practice to have a bare except. You should catch for a specific exception instead. I captured for Exception because that's as good as I can do without knowing what exceptions the methods might throw.

**Comment by ARJhe** [comment]
By transit to PostgreSQL, origin db contain NUL.
```
Traceback (most recent call last):
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\odoo\odoo11\odoo-11.0\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "d:\odoo\odoo11\addons\app_odoo_customize\models\app_theme_config_settings.py", line 652, in insert_yc_weight
    customer_id = self.env["yc.customer"].search([("code", '=', row.客戶代號)])
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 1481, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 3813, in _search
    self._cr.execute(query_str, where_clause_params)
  File "D:\odoo\odoo11\odoo-11.0\odoo\sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
ValueError: A string literal cannot contain NUL (0x00) characters.
```

**Comment by ARJhe** [comment]
final version, but we can fix the  fetch function to a selective option.(  fetchmany(500) > fetchmany(input) )
```python
 # 過磅單主檔
    @api.multi
    def insert_weight_main(self):
        try:
            cnxn = pyodbc.connect(
                'DRIVER={SQL Server}; SERVER=220.133.113.223,1433; DATABASE=ERPALL; UID=erplogin; PWD=@53272162')
            cursor = cnxn.cursor()
            cursor.execute("SELECT * FROM 過磅單主檔")
            rows = cursor.fetchmany(500)
            weight = self.env["yc.weight"].search([])
            sql = "delete from yc_weight"
            self._cr.execute(sql)

            for row in rows:
                # 先去除空白
                for x in range(len(row)):
                    if row[x] != None and type(row[x]) == str:
                        row[x] = row[x].replace(' ', '')

                driver_id = self.env["yc.driver"].search([("code", '=', row.司機代號)])
                person_id = self.env["yc.hr"].search([("code", '=', row.過磅人員)])
                factory_id = self.env["yc.factory"].search([("name", '=', row.所屬工廠)])
                if row.司機代號:
                    weight.create({
                        "name": row.過磅單號,
                        "in_out": row.分類,
                        "driver_id": driver_id.id,
                        "day": row.日期,
                        "weightime": row.時間,
                        "carno": row.車次序號,
                        "person_id": person_id.id,
                        "weighbridge": row.地磅序號,
                        "plate_no": row.車號,
                        "refine": row.調質重量,
                        "total": row.總重,
                        "carbur": row.滲碳重量,
                        "curbweight": row.空車重,
                        "other": row.其他重量,
                        "emptybucket": row.空桶重,
                        "net": row.淨重,
                        "purchase_times": row.進貨次數,
                        "ship_times": row.出貨次數,
                        "note": row.備註,
                        "other1": row.其他重量1,
                        "factory_id": factory_id.id,
                    })
        except Exception as e:
            pass
        return True

    # 過磅單項目檔
    @api.multi
    def insert_weight_details(self):
        try:
            cnxn = pyodbc.connect(
                'DRIVER={SQL Server}; SERVER=220.133.113.223,1433; DATABASE=ERPALL; UID=erplogin; PWD=@53272162')
            cursor = cnxn.cursor()
            weight = self.env["yc.weight"].search([]).name_get()
            _string = ''
            for x in range(len(weight)):
                if x != len(weight) - 1:
                    _string += "'" + weight[x][1] + "',"
                else:
                    _string += "'" + weight[x][1] + "'"
            # SELECT * FROM 過磅單項目檔 WHERE 過磅單號 IN('xxxxxxxxx','oooooo')
            db_sql = "SELECT * FROM 過磅單項目檔 WHERE 過磅單號 IN(%s)" % _string
            cursor.execute(db_sql)

            rows = cursor.fetchall()
            weight_item = self.env["yc.weight.details"].search([])
            sql = "delete from yc_weight_details"
            self._cr.execute(sql)

            for row in rows:

                if row.客戶代號 != None:
                    row.客戶代號 = row.客戶代號.strip("\x00")
                if row.加工廠代號 != None:
                    row.加工廠代號 = row.加工廠代號.strip("\x00")
                customer_id = self.env["yc.customer"].search([("code", '=', row.客戶代號)])
                processing_id = self.env["yc.processing"].search([("code", '=', row.加工廠代號)])
                name_id = self.env["yc.weight"].search([("name", "=", row.過磅單號)])

                weight_item.create({
                    "name": name_id.id,
                    "no": row.序號,
                    "customer_id": customer_id.id,
                    "processing_id": processing_id.id,
                    "note": row.備註,
                })
        except Exception as e:
            pass
        return True

    # 過磅單主檔 & 項目檔合併
    @api.multi
    def insert_yc_weight(self):
        insert_weight_main = ResConfigSettings.insert_weight_main
        insert_weight_details = ResConfigSettings.insert_weight_details
        funcs = insert_weight_main, insert_weight_details
        for func in funcs:
            func(self)
```
