### ISSUE TITLE
Compute field cause Expected singleton error in List View

### ISSUE THREAD

**Issue by ARJhe** [ARJhe/odoo11#70]
```
錯誤:
Odoo Server Error

Traceback (most recent call last):
  File "D:\odoo\odoo11\odoo-11.0\odoo\fields.py", line 939, in __get__
    value = record.env.cache.get(record, self)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 967, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 19477

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 4390, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\odoo\odoo11\odoo-11.0\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 334, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 876, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 898, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 4261, in search_read
    result = records.read(fields)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 2608, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 4785, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "D:\odoo\odoo11\odoo-11.0\odoo\fields.py", line 943, in __get__
    self.determine_value(record)
  File "D:\odoo\odoo11\odoo-11.0\odoo\fields.py", line 1054, in determine_value
    self.compute_value(recs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\fields.py", line 1010, in compute_value
    self._compute_value(records)
  File "D:\odoo\odoo11\odoo-11.0\odoo\fields.py", line 1001, in _compute_value
    getattr(records, self.compute)()
  File "d:\odoo\odoo11\addons_yc\yc_root\models\purchase.py", line 38, in _combine
    if self.processing_attache:
  File "D:\odoo\odoo11\odoo-11.0\odoo\fields.py", line 937, in __get__
    record.ensure_one()
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 4393, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: yc.purchase(19477, 19466, 19467, 19469, 19470, 19471, 19473, 19218, 19220, 19320, 19273, 19274, 19276, 19277, 19289, 19291, 19293, 19296, 19305, 19310, 19317, 19448, 19449, 19322, 19453)
```

**Comment by ARJhe** [comment]
```python
combine_abbrev = fields.Char('客戶', compute='_combine')

    @api.depends('processing_attache')
    def _combine(self):
            for rec in self:
                if rec.processing_attache:
                    _c = rec.processing_attache.customer_id.abbrev
                    _p = rec.processing_attache.processing_id.name
                    rec.combine_abbrev = _p + '-' + _c
```
