### ISSUE TITLE
Call reference xml template return error

### ISSUE THREAD

**Issue by ARJhe** [ARJhe/odoo11#78]
```python
    def get_report(self):
        if self.driver_id:
            data = {
                'ids': self.ids,
                'model': self._name,
                'form': {
                    'driver_id': self.driver_id.id,
                    'date_start': self.date_start,
                    'date_end': self.date_end,
                },
            }
            # use `module_name.report_id` as reference.
            return self.env.ref('action_yc_cargo_report').report_action(self, data=data)
```

```
錯誤:
Odoo Server Error

Traceback (most recent call last):
  File "D:\odoo\odoo11\odoo-11.0\odoo\tools\cache.py", line 84, in lookup
    r = d[key]
  File "D:\odoo\odoo11\odoo-11.0\odoo\tools\func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\tools\lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x0000025E7EEC8378>, 'action_yc_cargo_report')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\odoo\odoo11\odoo-11.0\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 334, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "d:\odoo\odoo11\addons_yc\yc_root\report\cargo.py", line 26, in get_report
    return self.env.ref('action_yc_cargo_report').report_action(self, data=data)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 794, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "d:\odoo\odoo11\odoo-11.0\odoo\addons\base\ir\ir_model.py", line 1356, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
  File "d:\odoo\odoo11\odoo-11.0\odoo\addons\base\ir\ir_model.py", line 1340, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "D:\odoo\odoo11\odoo-11.0\odoo\tools\cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "d:\odoo\odoo11\odoo-11.0\odoo\addons\base\ir\ir_model.py", line 1326, in xmlid_lookup
    module, name = xmlid.split('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by ARJhe** [comment]
solution:
--
lack of module_name on ref() method argument.
