### ISSUE TITLE
modol run AttributeError: 'yc.data.import' object has no attribute '_cnxn'

### ISSUE THREAD

**Issue by ARJhe** [ARJhe/odoo11#80]
while running server got this error, but it's fine in local server.

錯誤:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/custom/addons_yc/yc_data_import/models/yc_data_import.py", line 311, in processing_update
    self.connection_start()
  File "/odoo/custom/addons_yc/yc_data_import/models/yc_data_import.py", line 19, in connection_start
    self._cnxn = pyodbc.connect('DRIVER={SQL Server}; SERVER=192.168.2.102; DATABASE=ERPALL; UID=erplogin; PWD=@53272162')
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'SQL Server' : file not found (0) (SQLDriverConnect)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 334, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/addons_yc/yc_data_import/models/yc_data_import.py", line 363, in processing_update
    self.disconnction()
  File "/odoo/custom/addons_yc/yc_data_import/models/yc_data_import.py", line 24, in disconnction
    self._cnxn.close()
AttributeError: 'yc.data.import' object has no attribute '_cnxn'

```python
# 開始連線
    def connection_start(self):
        self._cnxn = pyodbc.connect('DRIVER={SQL Server}; SERVER=192.168.2.102; DATABASE=ERPALL; UID=erplogin; PWD=@53272162')
        print(' \033[42m \033[0m 資料庫開始連線.')

    # 結束連線
    def disconnction(self):
        self._cnxn.close()
        print(' \033[42m \033[0m 資料庫連線已結束.')
        time.sleep(5)
```

**Comment by ARJhe** [comment]
solution:
--
module name differ from model name
modeule name: YcDataImport
model name: YcDataImport > YcImportData
```python
class YcImportData(models.TransientModel):
    _inherit = 'res.config.settings'
    _name = 'yc.import.data'
```
