### ISSUE TITLE
open a file on sever

### ISSUE THREAD

**Issue by ARJhe** [ARJhe/odoo11#88]
install paramiko on ubuntu 16.04
`sudo apt install python3-cryptography`
`sudo apt install python3-paramiko`
cmd for ssh_public key
` cd ~/.ssh`

**Comment by ARJhe** [comment]
Reference
--
https://stackoverflow.com/questions/51738112/how-to-read-file-on-linux-server-from-windows

**Comment by ARJhe** [comment]
```py
client= ssh_client.open_sftp()
file = sftp_client.open('your_filename')
try:
    for line in file:
       #Do whatever you want for each line in the file     
finally:
    file.close()
```

**Comment by ARJhe** [comment]
Try
--
```py
import paramiko
import select
client = paramiko.SSHClient()
client.load_system_host_keys()
client.connect('172.31.39.149')
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 416, in connect
    self, server_hostkey_name, server_key
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 824, in missing_host_key
    "Server {!r} not found in known_hosts".format(hostname)
paramiko.ssh_exception.SSHException: Server '172.31.39.149' not found in known_hosts

```

**Comment by ARJhe** [comment]
```py
import paramiko
client = paramiko.SSHClient()
client.load_system_host_keys()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
key = paramiko.RSAKey.from_private_key_file('/tmp/sshppk/openssh_yc_root', password='yc_root')
client.connect('172.31.39.149', pkey=key)
stdin, stdout, stderr = client.exec_command('cat /proc/net/dev')
net_dump = stdout.readlines()
```

**Comment by ARJhe** [comment]
```
錯誤:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/addons_yc/yc_root/wizard/quality_wizard.py", line 481, in read_data_in_server
    client.connect(hostname, pkey=key)
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 311, in connect
    raise NoValidConnectionsError(errors)
  File "/usr/lib/python3/dist-packages/paramiko/ssh_exception.py", line 166, in __init__
    body = ', '.join([x[0] for x in addrs[:-1]])
TypeError: 'dict_keys' object is not subscriptable
```

**Comment by ARJhe** [comment]
```
futureWarning: CTR mode needs counter parameter, not IV self._cipher = factory.new(key, *args, **kwargs)
```

**Comment by ARJhe** [comment]
> ```
> futureWarning: CTR mode needs counter parameter, not IV self._cipher = factory.new(key, *args, **kwargs)
> ```
> 
> ## Reference
> https://stackoverflow.com/questions/42029415/paramiko-futurewarning-ctr-mode-needs-counter-parameter
> 
> [paramiko/paramiko@4752287](https://github.com/paramiko/paramiko/commit/4752287a7379da61245087ee7e35635a4e42bb3f)

```

>>> import paramiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 1651
    return self._cipher_info[name]['class'].new(key, self._cipher_info[name]['mode'], '', counter)
                                                                                                 ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by ARJhe** [comment]
> ```
> futureWarning: CTR mode needs counter parameter, not IV self._cipher = factory.new(key, *args, **kwargs)
> ```
> 
> ## Reference
> https://stackoverflow.com/questions/42029415/paramiko-futurewarning-ctr-mode-needs-counter-parameter
> 
> [paramiko/paramiko@4752287](https://github.com/paramiko/paramiko/commit/4752287a7379da61245087ee7e35635a4e42bb3f)

Worked at test mode, after use button call function, got this error.

```
錯誤:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/addons_yc/yc_root/wizard/quality_wizard.py", line 481, in read_data_in_server
    client.connect(hostname, pkey=key)
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 367, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 584, in _auth
    raise saved_exception
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 494, in _auth
    allowed_types = set(self._transport.auth_publickey(username, pkey))
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 1329, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/usr/lib/python3/dist-packages/paramiko/auth_handler.py", line 208, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
```

**Comment by ARJhe** [comment]
```py
hostname = '172.31.36.206'
        user = 'admin'
        port = '8069'
        password = 'admin'
        client = paramiko.SSHClient()
        client.load_system_host_keys()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        key = paramiko.RSAKey.from_private_key_file('/tmp/sshppk/openssh_yc_root', password='yc_root')
        client.connect(hostname, username=user, port=port, password=password, look_for_keys=False, pkey=key)
        stdin, stdout, stderr = client.exec_command('cat /tmp/yc_data/90106001.50t')
        net_dump = stdout.readlines()
        print(net_dump)
```
```
錯誤:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 1907, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/lib/python3/dist-packages/paramiko/packet.py", line 326, in readline
    buf += self._read_timeout(timeout)
  File "/usr/lib/python3/dist-packages/paramiko/packet.py", line 482, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/addons_yc/yc_root/wizard/quality_wizard.py", line 490, in read_data_in_server
    client.connect(hostname, username=user, port=port, password=password, look_for_keys=False, pkey=key)
  File "/usr/lib/python3/dist-packages/paramiko/client.py", line 325, in connect
    t.start_client()
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 493, in start_client
    raise e
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 1748, in run
    self._check_banner()
  File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 1911, in _check_banner
    raise SSHException('Error reading SSH protocol banner' + str(e))
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

**Comment by ARJhe** [comment]
maybe the answer is:

>You cannot just execute python function through ssh. ssh is just a tunnel with your code on one >side (client) and shell on another (server). You should execute shell commands on remote side.
>
>If using raw ssh code is not critical, i suggest fabric as library for writing administration tools. It >contains tools for easy ssh handling, file transferring, sudo, parallel execution and other.

Reference:
https://stackoverflow.com/questions/13201624/execute-local-python-script-over-sshclient-with-paramiko-in-remote-machine
