### ISSUE TITLE
After reinstall environment in ubuntu server can not load js file and png

### ISSUE THREAD

**Issue by ARJhe** [ARJhe/odoo11#91]
![2019-08-09](https://user-images.githubusercontent.com/34853697/62757723-dc067f80-baae-11e9-8112-55e36d5d751b.png)
![2019-08-09 (1)](https://user-images.githubusercontent.com/34853697/62757725-dd37ac80-baae-11e9-8f01-fb4a231bd024.png)

**Comment by ARJhe** [comment]
Reference
--
https://www.odoo.com/forum/help-1/question/404-errors-loading-js-css-png-50058

**Comment by ARJhe** [comment]
something wrong in costom_module

**Comment by ARJhe** [comment]
error happened just when modified odoo-server.conf

**Comment by ARJhe** [comment]
```xml
錯誤:
Odoo Server Error

Traceback (most recent call last):
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\cache.py", line 84, in lookup
    r = d[key]
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x000002C5B7BA4488>, 'yc_root.action_purchase_wizard')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\convert.py", line 644, in _tag_record
    f_val = _eval_xml(self, field, self.env)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\convert.py", line 139, in _eval_xml
    +_process("".join(etree.tostring(n, encoding='unicode') for n in node))
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\convert.py", line 128, in _process
    self.idref[id] = self.id_get(id)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\convert.py", line 727, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\convert.py", line 733, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "d:\odoo\odoo11_yc\odoo-11.0\odoo\addons\base\ir\ir_model.py", line 1340, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "d:\odoo\odoo11_yc\odoo-11.0\odoo\addons\base\ir\ir_model.py", line 1329, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: yc_root.action_purchase_wizard

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "d:\odoo\odoo11_yc\odoo-11.0\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "d:\odoo\odoo11_yc\odoo-11.0\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "d:\odoo\odoo11_yc\odoo-11.0\odoo\addons\base\module\module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "d:\odoo\odoo11_yc\odoo-11.0\odoo\addons\base\module\module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "d:\odoo\odoo11_yc\odoo-11.0\odoo\addons\base\module\module.py", line 543, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\modules\registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\modules\loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\modules\loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\modules\loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\modules\loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\convert.py", line 751, in parse
    exc_info[2]
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\convert.py", line 644, in _tag_record
    f_val = _eval_xml(self, field, self.env)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\convert.py", line 139, in _eval_xml
    +_process("".join(etree.tostring(n, encoding='unicode') for n in node))
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\convert.py", line 128, in _process
    self.idref[id] = self.id_get(id)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\convert.py", line 727, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\convert.py", line 733, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "d:\odoo\odoo11_yc\odoo-11.0\odoo\addons\base\ir\ir_model.py", line 1340, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "D:\odoo\odoo11_yc\odoo-11.0\odoo\tools\cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "d:\odoo\odoo11_yc\odoo-11.0\odoo\addons\base\ir\ir_model.py", line 1329, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: yc_root.action_purchase_wizard" while parsing file:/d:/odoo/odoo11_yc/addons_yc/yc_root/wizard/order_display_wizard.xml:3, near
<record model="ir.ui.view" id="yc_purchase_display_wizard">
        <field name="name">Purchase Wizard</field>
        <field name="model">yc.purchase</field>
        <field name="type">form</field>
        <field name="arch" type="xml">
            <data><form string="Purchase Report">
                <sheet>
                    <style>
                        .o_form_sheet{ background-color: ghostwhite; }
                    </style>
                    <script>
                        $(document).on('click', "label.btn", function(event){
                            var div = $('div #toggle_elf');
                            var btn = $("div[name='wizard_btn'] input");
                            var wizard = $('.open_the_door')
                            var comfirm = $("button[name='itself_update']");
                            if (btn.prop('checked')==true){
                                div.css('display','unset');
                                $('button[name="wizard_comfirm"]').attr("disabled", true);
                                $('div .hidden_on_bush').addClass('hide', 0);
                                comfirm.css({'display':'unset','color':'white','background-color':'#7c7bad'});
                                wizard[0].innerText = "關閉舊檔搜尋";
                                wizard.css("background-color","#568e8f");
                                wizard.hover(function(e) {
                                    $(this).css("background-color",e.type === "mouseenter"?"#568e8f":"#80b1b3")
                                });
                                comfirm.hover(function(e) {
                                    $(this).css("background-color",e.type === "mouseenter"?"#5f5e97":"#7c7bad");
                                });
                            }
                            else if (btn.prop('checked')==false){
                                div.css('display','none');
                                $('button[name="wizard_comfirm"]').attr("disabled", false);
                                $('div .hidden_on_bush').removeClass('hide', 0);
                                comfirm.css('display','none');
                                wizard[0].innerText = "開啟舊檔搜尋";
                                wizard.css("background-color","#5f5e97");
                                wizard.hover(function(e) {
                                    $(this).css("background-color",e.type === "mouseenter"?"#5f5e97":"#7c7bad")
                                });
                            }
                        });
                    </script>
                    <div style="width:100%;border-top:1px #f2f2f2 solid;border-bottom:1px #f2f2f2 solid;padding: 3px;background-color: #c9c9c9">
                        <label for="wizard_btn" string="開啟舊檔搜尋" class="btn btn-primary btn-sm open_the_door" rel="open_the_door" id="open_the_door"/>
                        <button type="object" name="itself_update" string="確定帶出" style="display:none;"/>
                        <field name="wizard_btn" style="display:none;"/>
                        <field name="remainder" readonly="1" style="position: fixed;left: 40%;font-size: 21px;color: white;                                       text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;" attrs="{'invisible':[('wizard_btn','=', True)]}"/>
                    </div>
                    <div style="height:10px;"/>
                    <div id="toggle_elf" style="display:none;background:#e6e6ff;">
                        <div style="background:#e6e6ff;">
                            <field name="ck1"/>
                            <label string="　　品名" style="font-weight:bold"/>
                            <field name="product_code" style="width:100px" options="{'no_open': True,'no_create': True}"/>
                            <span style="display:inline-block; width: 40px;"/>
                            <field name="ck2"/>
                            <label string="　　規格" style="font-weight:bold"/>
                            <field name="norm_code" style="width:100px" options="{'no_open': True,'no_create': True}"/>
                            <span style="display:inline-block; width: 40px;"/>
                            <field name="ck3"/>
                            <label string="　　長度" style="font-weight:bold"/>
                            <field name="len_code" style="width:100px" options="{'no_open': True,'no_create': True}"/>
                            <br/>
                            <field name="ck7"/>
                            <label string="強度級數" style="font-weight:bold"/>
                            <field name="strength_level" style="width:100px" options="{'no_open': True,'no_create': True}"/>
                            <span style="display:inline-block; width: 40px;"/>
                            <field name="ck4"/>
                            <label string="品名分類" style="font-weight:bold"/>
                            <field name="clsf_code" style="width:100px" options="{'no_open': True,'no_create': True}"/>
                            <span style="display:inline-block; width: 40px;"/>
                            <field name="ck5"/>
                            <label string="加工方式" style="font-weight:bold"/>
                            <field name="proces_code" style="width:100px" options="{'no_open': True,'no_create': True}"/>
                            <br/>
                            <field name="ck6"/>
                            <label string="　　材質" style="font-weight:bold"/>
                            <field name="txtur_code" style="width:100px" options="{'no_open': True,'no_create': True}"/>
                            <span style="display:inline-block; width: 40px;"/>
                            <field name="ck8"/>
                            <label string="線材爐號" style="font-weight:bold"/>
                            <field name="wire_furn" style="width:100px" options="{'no_open': True,'no_create': True}"/>
                            <span style="display:inline-block; width: 40px;"/>

                        </div>
                        <field name="itself_ids" widget="many2many">
                            <tree create="false" delete="false" string="Purchase Details" editable="top">
                                <!--<button name="itself_update" type="object" icon="fa fa-check-square-o"/>-->
                                <field name="wizard_check" string=" " widget="checkbox"/>
                                <field name="name" string="工令" readonly="1"/>
                                <field name="customer_id" string="客戶" readonly="1" options="{'no_open': True,'no_create': True}"/>
                                <field name="norm_code" readonly="1" options="{'no_open': True,'no_create': True}"/>
                                <field name="surfhrd" string="表面" readonly="1"/>
                                <field name="corehrd" string="心部" readonly="1"/>
                                <field name="tensihrd" string="抗拉" readonly="1"/>
                                <field name="carburlayer" string="滲碳" readonly="1"/>
                                <field name="torsion" readonly="1"/>
                                <field name="tempturing2" string="回火" readonly="1"/>
                                <field name="order_furn" string="預排爐" readonly="1" options="{'no_open': True,'no_create': True}"/>
                            </tree>
                        </field>

                    </div>
                    <div style="">
                        <div class="hidden_on_bush">
                            <label string="工令號碼" style="font-weight:bold"/>
                            <field name="name" style="width:100px" readonly="1"/>
                            <span style="display:inline-block; width: 20px;"/>　
                            <label string="進貨日期" style="font-weight:bold"/>
                            <field name="day" style="width:120px" readonly="1"/>
                            <span style="display:inline-block; width: 20px;"/>　
                            <label string="客戶" style="font-weight:bold"/>
                            <field name="customer_id" style="width:100px" readonly="1" options="{'no_open': True,'no_create': True}"/>
                            <span style="display:inline-block; width: 20px;"/>　
                            <label string="客戶批號" style="font-weight:bold"/>
                            <field name="batch" style="width:100px" readonly="1"/>
                            <br/>
                            <span style="display:inline-block; width: 27px;"/>
                            <!--<field name="ck1"/>-->
                            <label string="品名" style="font-weight:bold"/>
                            <field name="product_code" style="width:180px" options="{'no_open': True,'no_create': True}" readonly="1"/>
                            <span style="display:inline-block; width: 20px;"/>　
                            <!--<field name="ck2"/>-->
                            <label string="規格" style="font-weight:bold" options="{'no_open': True,'no_create': True}"/>
                            <field name="norm_code" style="width:100px" options="{'no_open': True,'no_create': True}" readonly="1"/>
                            <span style="display:inline-block; width: 20px;"/>　
                            <!--<field name="ck3"/>-->
                            <field name="len_code" style="width:100px" options="{'no_open': True,'no_create': True}" readonly="1"/>
                            <field name="len_descript" style="width:100px" readonly="1"/>
                            <br/>
                            <!--<field name="ck4"/>-->
                            <label string="品名分類" style="font-weight:bold"/>
                            <field name="clsf_code" style="width:150px" options="{'no_open': True,'no_create': True}" readonly="1"/>
                            <span style="display:inline-block; width: 10px;"/>
                            <!--<field name="ck6"/>-->
                            <label string="材質" style="font-weight:bold"/>
                            <field name="txtur_code" style="width:100px" options="{'no_open': True,'no_create': True}" readonly="1"/>
                            <span style="display:inline-block; width: 10px;"/>　
                            <label string="表面處理" style="font-weight:bold"/>
                            <field name="surface_code" style="width:80px" readonly="1" options="{'no_open': True,'no_create': True}"/>
                            <span style="display:inline-block; width: 10px;"/>
                            <!--<field name="ck7"/>-->
                            <label string="強度級數" style="font-weight:bold"/>
                            <field name="strength_level" style="width:100px" options="{'no_open': True,'no_create': True}" readonly="1"/>
                            <span style="display:inline-block; width: 10px;"/>　
                            <label string="牙分類" style="font-weight:bold"/>
                            <field name="fullorhalf" style="width:80px" readonly="1"/>
                            <br/>
                            <!--<field name="ck5"/>-->
                            <label string="加工方式" style="font-weight:bold"/>
                            <field name="proces_code" style="width:100px" options="{'no_open': True,'no_create': True}" readonly="1"/>
                            <span style="display:inline-block; width: 20px;"/>　
                            <label string="數量　" style="font-weight:bold" class="oe_inline"/>
                            <field name="num1" style="width:70px" readonly="1"/>　
                            <field name="unit1" nolabel="1" style="width:50px" readonly="1" options="{'no_open': True,'no_create': True}"/>
                            <field name="num2" style="width:70px" readonly="1"/>
                            <field name="unit2" nolabel="1" style="width:50px" readonly="1" options="{'no_open': True,'no_create': True}"/>
                            <field name="num3" style="width:70px" readonly="1"/>
                            <field name="unit3" nolabel="1" style="width:50px" readonly="1" options="{'no_open': True,'no_create': True}"/>
                            <field name="num4" style="width:70px" readonly="1"/>
                            <field name="unit4" nolabel="1" style="width:50px" readonly="1" options="{'no_open': True,'no_create': True}"/>　
                            <br/>
                            <span style="display:inline-block; width: 27px;"/>
                            <label string="淨重" style="font-weight:bold"/>
                            <field name="net" style="width:60px" readonly="1"/>
                            <span style="display:inline-block; width: 20px;"/>　
                            <label string="表面硬度" style="font-weight:bold"/>
                            <field name="surfhrd" style="width:90px" readonly="1"/>
                            <span style="display:inline-block; width: 20px;"/>　
                            <label string="心部硬度" style="font-weight:bold"/>
                            <field name="corehrd" style="width:90px" readonly="1"/>
                            <span style="display:inline-block; width: 20px;"/>　
                            <label string="存放地點" style="font-weight:bold"/>
                            <field name="storeplace" style="width:100px" readonly="1"/>
                            <br/>
                            <label string="抗拉強度" style="font-weight:bold"/>
                            <field name="tensihrd" style="width:90px" readonly="1"/>
                            <span style="display:inline-block; width: 20px;"/>　
                            <label string="　滲碳層" style="font-weight:bold"/>
                            <field name="carburlayer" style="width:90px" readonly="1"/>
                            <span style="display:inline-block; width: 20px;"/>　
                            <label string="預排爐號" style="font-weight:bold"/>
                            <field name="order_furn" style="width:60px" readonly="1" options="{'no_open': True,'no_create': True}"/>
                            <span style="display:inline-block; width: 20px;"/>　
                            <!--<field name="ck8"/>-->
                            <label string="線材爐號" style="font-weight:bold"/>
                            <field name="wire_furn" style="width:100px" readonly="1"/>
                            <span style="display:inline-block; width: 20px;"/>
                            <!--<button string="搜尋舊檔" type="action" class="oe_highlight"-->
                            <!--style=""-->
                            <!--name="%(action_purchase_wizard)d" context="{'wizard':True}"/>-->
                            <!--<button string="搜尋舊檔(測試版)" type="object" class="oe_highlight"-->
                            <!--name="open_wizard"-->
                            <!--/>-->
                            <br/>
                            <label string="製造日期" style="font-weight:bold"/>
                            <field name="produceday1" style="width: 120px" readonly="1"/>
                            <field name="ptime1" nolabel="1" style="width: 50px" readonly="1"/>
                            <span style="display:inline-block; width: 10px;"/>
                            <label string="班別" style="font-weight:bold"/>
                            <field name="shift1" style="width: 80px;" readonly="1" options="{'no_open': True,'no_create': True}"/>
                            <span style="display:inline-block; width: 30px;"/>
                            <label string="操作人員" style="font-weight:bold"/>
                            <field name="op1" style="width: 100px" readonly="1" options="{'no_open': True,'no_create': True}"/>
                            <label string="品管人員" style="font-weight:bold"/>
                            <field name="qc" style="width:100px" readonly="1" options="{'no_open': True,'no_create': True}"/>
                            <br/>
                        <!--</div>-->
                        <!--<div>-->
                            <label string="　　流量" style="font-weight:bold"/>
                            <field name="flow" style="width: 80px"/>
                            <span style="display:inline-block; width: 20px;"/>
                            <label string="CP值" style="font-weight:bold"/>
                            <field name="cp" style="width: 90px"/>
                            <span style="display:inline-block; width: 20px;"/>
                            <label string="氨值" style="font-weight:bold"/>
                            <field name="nh31" style="width: 70px"/>
                            <span style="display:inline-block; width: 20px;"/>
                            <label string="支" style="font-weight:bold"/>
                            <field name="nh32" style="width: 70px"/>
                            <span style="display:inline-block; width: 20px;"/>
                            <label string="第" style="font-weight:bold"/>
                            <field name="nh33" style="width: 70px"/>
                            <span style="display:inline-block; width: 20px;"/>
                            <label string="支" style="font-weight:bold"/>
                            <field name="nh34" style="width: 70px"/>
                            <br/>
                            <label string="　加熱爐" style="font-weight:bold"/>
                            <field name="heat2" style="width: 80px;position: relative;left: 80px;" default_focus="1"/>
                            <field name="heat1" style="width: 80px;position: relative;left: -80px;"/>

                            <field name="heat3" style="width: 80px"/>
                            <field name="heat4" style="width: 80px"/>
                            <field name="heat5" style="width: 80px"/>
                            <field name="heat6" style="width: 80px"/>
                            <field name="heat7" style="width: 80px"/>
                            <field name="heat8" style="width: 80px"/>
                            <br/>
                            <label string="　　油溫" style="font-weight:bold"/>
                            <field name="heattemp" style="width: 80px"/>
                            <span style="display:inline-block; width: 10px;"/>
                            <label string="速度" style="font-weight:bold"/>
                            <field name="heatsped" style="width: 80px"/>
                            <br/>
                            <label string="　回火爐" style="font-weight:bold"/>
                            <field name="tempturing2" style="width: 80px;position: relative;left: 80px;"/>
                            <field name="tempturing1" style="width: 80px;position: relative;left: -80px;"/>

                            <field name="tempturing3" style="width: 80px"/>
                            <field name="tempturing4" style="width: 80px"/>
                            <field name="tempturing5" style="width: 80px"/>
                            <field name="tempturing6" style="width: 80px"/>
                            <span style="display:inline-block; width: 10px;"/>
                            <label string="速度" style="font-weight:bold"/>
                            <field name="tempturisped" style="width: 80px"/>
                            <br/>
                            <label string="注意事項" style="font-weight:bold"/>
                            <field name="notices1" style="width:200px"/>
                            <field name="notices2" style="width:200px"/>
                            <field name="notices3" style="width:200px"/>
                            <br/>
                            <label string="品管備註" style="font-weight:bold"/>
                            <field name="qcnote1" style="width:200px"/>
                            <field name="qcnote2" style="width:200px"/>
                            <field name="qcnote3" style="width:200px"/>
                            <br/>
                            <label string="製造備註" style="font-weight:bold"/>
                            <field name="prodnote1" style="width:200px"/>
                            <field name="prodnote2" style="width:200px"/>
                            <field name="prodnote3" style="width:200px"/>
                        </div>
                    </div>
                </sheet>
            </form>
            <footer>
                <!--attrs="{'invisible': [('account_setup_company_data_done','=',False)]}"-->
                <button name="wizard_comfirm" string="修改完畢" type="object" class="oe_highlight"/>
                <button string="取消" special="cancel"/>
            </footer>
        </data></field>
    </record>
```

**Comment by ARJhe** [comment]
while test process_review wizard
```
console:
Menu no action found web test 04 will fail
```

**Comment by ARJhe** [comment]
> something wrong in costom_module
> 
> * error happened just when modified odoo-server.conf
> * install worked in server after remove wizard folder :confirmed
> * confirm error cause by quality wizard.
> * after mute quality declares form `wizard>__init__.py` and manifest of it, origin project can work in server.
> * possible error: undefined module import by py file.
> * the undefined module is paramiko

- install paramiko on ubuntu

`sudo apt-get install python3-paramiko`

Reference
https://askubuntu.com/questions/1093243/error-while-using-pip3-to-install-paramiko-on-ubuntu-16-04
