### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'upper'

### ISSUE THREAD

**Issue by ARJhe** [ARJhe/odoo11#92]
Traceback (most recent call last):
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\odoo\odoo11\odoo-11.0\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 334, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "d:\odoo\odoo11\odoo-11.0\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\models.py", line 1079, in default_get
    defaults[name] = field.default(self)
  File "d:\odoo\odoo11\addons_yc\yc_root\models\weight.py", line 17, in <lambda>
    weightime = fields.Char("過磅時間", default=lambda self: self._get_time())
  File "d:\odoo\odoo11\addons_yc\yc_root\models\weight.py", line 64, in _get_time
    now = dt.now(pytz.timezone(user_tz)).strftime("%Y%m%d%H%M%S")
  File "D:\odoo\python35_odoo11_venv\lib\site-packages\pytz\__init__.py", line 163, in timezone
    if zone.upper() == 'UTC':
AttributeError: 'bool' object has no attribute 'upper'

**Comment by ARJhe** [comment]
must set user timezone because of function line:
`now = dt.now(pytz.timezone(user_tz)).strftime("%Y%m%d%H%M%S")`
