### ISSUE TITLE
AttributeError: 'res.users' object has no attribute 'chatter_position'

### ISSUE THREAD

**Issue by ARJhe** [ARJhe/odoo11#97]
2019-08-16 06:23:03,034 14564 INFO odoo_test_5 odoo.addons.base.ir.ir_http: Generating routing map
2019-08-16 06:23:03,973 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,975 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,976 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,977 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,979 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,980 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,981 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,983 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,984 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,985 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,986 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,987 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,988 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,989 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,992 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,993 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,994 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,994 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,995 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,996 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,997 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,998 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:03,999 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,002 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,005 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,007 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,009 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,011 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,013 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,013 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,015 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,016 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,017 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,018 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,020 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,021 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,023 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,025 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,027 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,028 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,030 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,032 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,033 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,035 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,062 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,064 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,066 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,068 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,071 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,076 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,077 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,079 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,081 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:04,083 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,833 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,891 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,975 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,976 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,977 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,978 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,979 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,980 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,981 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,982 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,983 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,984 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,988 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,988 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,991 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,991 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,993 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,994 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,995 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,996 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,997 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,998 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:05,999 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:06,000 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:06,545 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:06,559 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:06,562 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:06,568 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:06,572 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:06,573 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:06,586 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:06,588 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:06,590 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:06,601 14564 WARNING odoo_test_5 odoo.modules.module: module web_responsive: module not found
2019-08-16 06:23:06,646 14564 INFO odoo_test_5 odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [730]
2019-08-16 06:23:06,864 14564 INFO odoo_test_5 werkzeug: 127.0.0.1 - - [16/Aug/2019 06:23:06] "GET /web HTTP/1.1" 500 -
2019-08-16 06:23:06,870 14564 INFO odoo_test_5 odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [730]
2019-08-16 06:23:06,881 14564 ERROR odoo_test_5 werkzeug: Error on request:
Traceback (most recent call last):
  File "D:\odoo\python35_odoo11_venv\lib\site-packages\werkzeug\serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "D:\odoo\python35_odoo11_venv\lib\site-packages\werkzeug\serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "D:\odoo\odoo11\odoo-11.0\odoo\service\server.py", line 260, in app
    return self.app(e, s)
  File "D:\odoo\odoo11\odoo-11.0\odoo\service\wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "D:\odoo\odoo11\odoo-11.0\odoo\service\wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 1320, in __call__
    return self.dispatch(environ, start_response)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 1294, in __call__
    return self.app(environ, start_wrapped)
  File "D:\odoo\python35_odoo11_venv\lib\site-packages\werkzeug\wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 1492, in dispatch
    result = ir_http._dispatch()
  File "d:\odoo\odoo11\odoo-11.0\addons\web_editor\models\ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "d:\odoo\odoo11\odoo-11.0\odoo\addons\base\ir\ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "d:\odoo\odoo11\odoo-11.0\odoo\addons\base\ir\ir_http.py", line 182, in _handle_exception
    return request._handle_exception(exception)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 770, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\odoo\odoo11\odoo-11.0\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "d:\odoo\odoo11\odoo-11.0\odoo\addons\base\ir\ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 829, in dispatch
    r = self._call_function(**self.params)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 341, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 337, in checked_call
    result.flatten()
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 1271, in flatten
    self.response.append(self.render())
  File "D:\odoo\odoo11\odoo-11.0\odoo\http.py", line 1264, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "d:\odoo\odoo11\odoo-11.0\odoo\addons\base\ir\ir_ui_view.py", line 1211, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "d:\odoo\odoo11\odoo-11.0\addons\web_editor\models\ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "d:\odoo\odoo11\odoo-11.0\odoo\addons\base\ir\ir_ui_view.py", line 1220, in render
    return self.env[engine].render(self.id, qcontext)
  File "d:\odoo\odoo11\odoo-11.0\odoo\addons\base\ir\ir_qweb\ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "d:\odoo\odoo11\odoo-11.0\odoo\addons\base\ir\ir_qweb\qweb.py", line 272, in render
    self.compile(template, options)(self, body.append, values or {})
  File "d:\odoo\odoo11\odoo-11.0\odoo\addons\base\ir\ir_qweb\qweb.py", line 350, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: 'res.users' object has no attribute 'chatter_position'
Traceback (most recent call last):
  File "d:\odoo\odoo11\odoo-11.0\odoo\addons\base\ir\ir_qweb\qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_171_19
  File "<template>", line 2, in body_call_content_18
AttributeError: 'res.users' object has no attribute 'chatter_position'

**Comment by ARJhe** [comment]
remove web_responsive accidentally.
